anon_resume/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('resume.urls'))
]

resume/urls.py
from django.conf.urls import url
from . import views

app_name = 'resume'
urlpatterns = [
	url(r'^resume$', views.resume_list, name='resume_list'),
	url(r'upload_resume$', views.upload_resume, name='upload_resume'),
	url(r'upload_old$', views.upload, name='upload'),
	url(r'^$', views.home, name='home'),
]

resume/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Resume(models.Model):
     old_resume = models.ImageField(upload_to='old_resumes/')
     new_resume = models.ImageField(upload_to='new_resumes/')
     dept = models.TextField(max_length=20)
     extra = models.TextField(max_length=40)

resume/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Resume
# Create your views here.
depts = ['Engineering', 'People', 'Data Science', 'Services', 'Commercial', 'Finance', 'Global Business Operations']
depts.sort()

def home(request):
	return render(request, 'resume/index.html', {})

def resume_list(request):
	print("lesgitit")
	return render(request, 'resume/resume_list.html', {})

def upload_resume(request):
	return render(request, 'resume/upload_resume.html', {'depts' : depts})


def upload(request):
	new_entry = Resume(old_resume = request.FILES['up_res'], dept=request.POST['dept'], extra=request.POST['extra'])
	new_entry.save()
	print "File name: ", new_entry.old_resume.name
	print "Dept: ", new_entry.dept
	print "Primary key: ", new_entry.pk
	print "hi"
	return render(request, 'resume/upload_resume.html', {'depts': depts})

resume/templates/resume/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>4 Col Portfolio - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/4-col-portfolio.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'resume/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'resume/4-col-portfolio.css' %}" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Page Heading
                    <small>Secondary Text</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
            <div class="col-md-3 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/750x450" alt="">
                </a>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Pagination -->
        <div class="row text-center">
            <div class="col-lg-12">
                <ul class="pagination">
                    <li>
                        <a href="#">&laquo;</a>
                    </li>
                    <li class="active">
                        <a href="#">1</a>
                    </li>
                    <li>
                        <a href="#">2</a>
                    </li>
                    <li>
                        <a href="#">3</a>
                    </li>
                    <li>
                        <a href="#">4</a>
                    </li>
                    <li>
                        <a href="#">5</a>
                    </li>
                    <li>
                        <a href="#">&raquo;</a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

resume/templates/resume/resume_list.html
<html>
    <p>Hi there!</p>
    <p>It works!</p>
</html>

resume/templates/resume/upload_resume.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'resume/style.css' %}" />
<title>Upload New Resume</title>

<div class="form">
<div class="title">Upload New Resume</div>
<form action="{% url 'resume:upload' %}" enctype="multipart/form-data" method="post">
{% csrf_token %}

    <div class="entry">
        <input type="file" name="up_res" size="40" id="up_res">
    </div>
    <br>
    <div class="entry">
        <label for="dept">Department: </label>
        <select name="dept" id="dept">
            {% for d in depts %}
                <option value="{{ d }}">{{ d }}</option>
            {% endfor %}
        </select>
    </div>
    <br>
    <div class="entry2">
        <span>
            <label for="extra">Extra information: </label>
            <input type="text" name="extra" id="extra" value="">
        </span>

    </div>
    <br>
    <div class="submit">
    <span id="search"><button type="submit">Submit</button></span>
    </div>
</form>
</div>